/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "Platform_Type.h"
//clock
#define RCC_BASE           0x40021000
#define RCC_APB2ENR        *(vuint32*)(RCC_BASE+0x18)
//GPIO
#define GPIOA_BASE 		   0x40010800
#define GPIOA_CRL          *((vuint32*)(GPIOA_BASE+0x00))
#define GPIOA_CRH          *((vuint32*)(GPIOA_BASE+0x04))
#define GPIOA_ODR          *((vuint32*)(GPIOA_BASE+0x0c))
 //EXTI
#define EXTI_BASE			0x40010400
#define EXTI_IMR         	*((vuint32*)(EXTI_BASE+0x00))
#define EXTI_RTSR			 *((vuint32*)(EXTI_BASE+0x08))
#define EXTI_PR				 *((vuint32*)(EXTI_BASE+0x14))

//AFIO
#define AFIO_BASE			  0x40010000
#define AFIO_EXTICR1          *((vuint32*)(AFIO_BASE+0x08))

//NVIC
#define NVIC_ISER0		      *((vuint32*)(0xE000E100))


void clock_init()
{
	// enable GBIOA clock
	RCC_APB2ENR |= 1 << 2;
	//enable AFIO clock
	RCC_APB2ENR |= (1<<0);
}
void GPIO_init()
{   //put GPIOA pin 13 out
	GPIOA_CRH &= 0xff0fffff;
	GPIOA_CRH |= 0x00200000;
	// GPIOA pin 0 floating input
	GPIOA_CRL |= (1<<2);
}

void main(void) {


	GPIO_init();
	clock_init();
	AFIO_EXTICR1|=(0b000<<0);
	//enable rising edge
	EXTI_IMR  |=(1<<0);
	//enable line 0 interupt mask
	EXTI_RTSR |=(1<<0);
	//Enable NVIC IRQ6
	NVIC_ISER0 |=(1<<6);

	while(1);




}
void EXTI0_IRQHandler(void)
{
	//toggle bit 13 portA
	GPIOA_ODR ^=(1<<13);

	//clear Pending register
	EXTI_PR |=(1<<0);


}
