/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "Platform_Type.h"
//clock
#define RCC_BASE           0x40021000
#define RCC_APB2ENR        *(vuint32*)(RCC_BASE+0x18)


//GPIO
#define GPIOA_BASE         0x40010800
#define GPIOA_CRL          *((vuint32*)(GPIOA_BASE+0x00))
#define GPIOA_CRH          *((vuint32*)(GPIOA_BASE+0x04))
#define GPIOA_ODR          *((vuint32*)(GPIOA_BASE+0x0c))
#define GPIOA_IDR          *((vuint32*)(GPIOA_BASE+0x08))


#define GPIOB_BASE         0x40010C00
#define GPIOB_CRL          *((vuint32*)(GPIOB_BASE+0x00))
#define GPIOB_CRH          *((vuint32*)(GPIOB_BASE+0x04))
#define GPIOB_ODR          *((vuint32*)(GPIOB_BASE+0x0c))



void clock_init()
{
    // enable GBIOA clock
    RCC_APB2ENR |= 1 << 2;
    // enable GBIOB clock
    RCC_APB2ENR |= 1 << 3;

}
void GPIO_init()
{
//A1 floating input
    GPIOA_CRL =0;
    GPIOA_CRL &=~(0b11<<4);
    GPIOA_CRL |= (0b01<<6);
//A13 floating input
        GPIOA_CRH =0;
        GPIOA_CRH &=~(0b11<<20);
        GPIOA_CRH |= (0b01<<22);
//B1 Output
        GPIOB_CRL |= (0b01<<4);
        GPIOB_CRL &=~(0b11<<6);
//B13 Output
        GPIOB_CRH |= (0b01<<20);
        GPIOB_CRH &=~(0b11<<22);

}

void my_wait(int time)
{ int i ,j;
    for(i=0;i<time;i++)
        for(j=0;j<255;j++);

}

int main(void)
{

    clock_init();
    GPIO_init();



    while(1)
    {

        if (((GPIOA_IDR>>1)&1)==0)
        {
            GPIOB_ODR ^= (1<<1);
            while (((GPIOA_IDR>>1)&1)==0);
        }
        if ((GPIOA_IDR>>13)==1)
        {
            GPIOB_ODR ^= (1<<13);

        }
        my_wait(1);

    }


return 0;

}
